version: '3'

services: 

  ####
  # NODE CONTAINER
  ####
  server: 
    build: ./server
    expose: 
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/app/pokedex-microapp-server/src
      - ./server/dist:/app/pokedex-microapp-server/dist

  ####
  # Frontend Container
  ####
  frontend:
    build: ./frontend
    environment: 
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports: 
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./frontend/src:/app/pokedex-microapp-frontend/src
      - ./frontend/public:/app/pokedex-microapp-frontend/public
    links:
      - server
    command: npm run start
